apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiapx

labels:
  - pairs:
      app.kubernetes.io/part-of: fiapx
    includeSelectors: false

resources:
  - namespace.yaml
  - api.yaml
  - auth.yaml
  - worker.yaml
  - notification.yaml
  - app.yaml
  - postgres.yaml
  - mongo.yaml
  - redis.yaml
  - rabbitmq.yaml
  - minio.yaml
  - monitoring.yaml
  - ingress.yaml

configMapGenerator:
  - name: fiapx-config
    envs:
      - config.env
  - name: postgres-init
    files:
      - init.sql=postgres/init.sql

secretGenerator:
  - name: fiapx-secrets
    envs:
      - secrets.env
